"""Put the existing success charts first in the user's actual W&B workspace.

The public Workspace SDK rejects personal workspaces. This utility uses the same
GraphQL view operations while retaining the raw personal view JSON, including
fields the Workspace SDK does not currently preserve. Dry-run is the default.

Existing automatic sections remain enabled and accessible, but collapsed. Their
panels are generated by the app and cannot be retained by turning generation off.
No run, metric, filter, or training setting is changed.
"""
from __future__ import annotations

import argparse
import copy
from datetime import datetime, timezone
import json
from pathlib import Path
import uuid


READ_QUERY = """
query SuccessWorkspace($entity: String!, $project: String!) {
  viewer { username }
  project(name: $project, entityName: $entity) {
    allViews(viewType: "project-view") {
      edges { node { id name displayName spec } }
    }
  }
}
"""

WRITE_QUERY = """
mutation SuccessWorkspace($id: ID, $entityName: String, $projectName: String,
  $type: String, $name: String, $displayName: String, $spec: String) {
  upsertView(input: {id: $id, entityName: $entityName,
    projectName: $projectName, type: $type, name: $name,
    displayName: $displayName, spec: $spec, createdUsing: WANDB_SDK}) {
    view { id name }
    inserted
  }
}
"""

SUCCESS_GROUP_LABELS = {
    "cat_goal_success_rate": "Original environments",
    "ordinary_clutter_goal_success_rate": "Ordinary clutter",
    "hand_protection_goal_success_rate": "Hand protection",
}


def read_views(api, execute, entity, project):
    result = execute(api, READ_QUERY, {"entity": entity, "project": project})
    if result.get("project") is None:
        raise RuntimeError("Project unavailable; no changes made")
    views = {
        edge["node"]["name"]: edge["node"]
        for edge in result["project"]["allViews"]["edges"]
    }
    return result["viewer"]["username"], views


def chart_signature(section):
    return [
        (p.get("config", {}).get("chartTitle"),
         tuple(p.get("config", {}).get("metrics", [])))
        for p in section.get("panels", [])
    ]


def prepare(personal, saved):
    original = json.loads(personal["spec"])
    proposal = copy.deepcopy(original)
    source_spec = json.loads(saved["spec"])
    source_sections = source_spec["section"]["panelBankConfig"]["sections"]
    desired = copy.deepcopy(next(s for s in source_sections if s["name"] == "Success rates"))
    if len(desired.get("panels", [])) != 3:
        raise RuntimeError("Expected exactly three existing success charts")
    # A project workspace can compare several runs at once. Give each success
    # metric its own chart instead of overlaying three metrics for every run.
    split_panels = []
    for panel in desired["panels"]:
        config = panel["config"]
        for metric in config["metrics"]:
            split_panel = copy.deepcopy(panel)
            split_config = split_panel["config"]
            split_config["metrics"] = [metric]
            if metric.startswith("validation/stochastic/"):
                label = SUCCESS_GROUP_LABELS[metric.removeprefix("validation/stochastic/")]
                split_config["chartTitle"] = f"{label}: stochastic success"
            elif metric.startswith("validation/"):
                label = SUCCESS_GROUP_LABELS[metric.removeprefix("validation/")]
                split_config["chartTitle"] = f"{label}: deterministic success"
            elif metric == "training/goal_success_rate":
                label = "Training episodes"
                split_config["chartTitle"] = "Training success: completed episodes"
            else:
                raise RuntimeError(f"Unexpected success metric: {metric}")
            split_config["overrideSeriesTitles"] = {metric: label}
            split_panels.append(split_panel)
    if len(split_panels) != 7:
        raise RuntimeError("Expected seven individual success metrics")
    desired["panels"] = split_panels
    # Three rows keep all seven panels visible in the first section.
    desired.setdefault("flowConfig", {})["rowsPerPage"] = 3
    signature = chart_signature(desired)

    sections = proposal["section"]["panelBankConfig"]["sections"]
    existing = next(
        (s for s in sections
         if s.get("name") == "Success rates" and chart_signature(s) == signature),
        None,
    )
    if existing is not None:
        sections.remove(existing)
        first = existing
    else:
        first = copy.deepcopy(desired)
        first["__id__"] = uuid.uuid4().hex[:11]
        for panel in first["panels"]:
            panel["__id__"] = uuid.uuid4().hex[:11]

    first.update(isOpen=True, isPanelsAuto=False, pinned=True)
    first.pop("defaultName", None)
    for panel in first["panels"]:
        panel["isAuto"] = False
    for section in sections:
        section["isOpen"] = False
    sections.insert(0, first)

    # Deliberately leave workspaceSettings/settings and all other blocks intact.
    # Auto charts are absent from stored panels and generated by the browser.
    return original, proposal, existing is not None


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--entity", default="skvayzer")
    parser.add_argument("--project", default="CAT-wholebody")
    parser.add_argument("--personal-view", default="nw-nwuserskvayzer-w")
    parser.add_argument("--saved-view", default="nw-78xpyp21m83-v")
    parser.add_argument("--backup", type=Path, required=True,
                        help="New JSON file holding the original and proposed raw views")
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    import wandb
    from wandb_workspaces._graphql import execute_graphql

    api = wandb.Api()
    username, views = read_views(api, execute_graphql, args.entity, args.project)
    if args.personal_view != f"nw-nwuser{username}-w":
        raise RuntimeError("Target must be the authenticated user's personal workspace")
    personal = views[args.personal_view]
    saved = views[args.saved_view]
    original, proposed, reused = prepare(personal, saved)
    review = {
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "apply_requested": args.apply,
        "entity": args.entity,
        "project": args.project,
        "original_personal_view": personal,
        "source_saved_view": saved,
        "proposed_spec": proposed,
    }
    args.backup.parent.mkdir(parents=True, exist_ok=True)
    with args.backup.open("x") as handle:
        json.dump(review, handle, indent=2)
        handle.write("\n")

    original_sections = original["section"]["panelBankConfig"]["sections"]
    proposed_sections = proposed["section"]["panelBankConfig"]["sections"]
    print(json.dumps({
        "action": "apply" if args.apply else "dry-run",
        "backup": str(args.backup),
        "view": personal["displayName"],
        "id": personal["id"],
        "reusing_success_section": reused,
        "existing_sections_preserved": len(original_sections),
        "first_section": proposed_sections[0]["name"],
        "first_section_panels": len(proposed_sections[0]["panels"]),
        "all_other_sections_collapsed": all(not s["isOpen"] for s in proposed_sections[1:]),
        "auto_panel_generation": "unchanged; existing automatic charts remain accessible",
        "url": f"https://wandb.ai/{args.entity}/{args.project}?nw=nwuser{username}",
    }, indent=2))
    if not args.apply:
        return

    # Refuse to overwrite edits made while the proposal/backup was generated.
    _, current = read_views(api, execute_graphql, args.entity, args.project)
    latest = current[args.personal_view]
    if latest["id"] != personal["id"] or json.loads(latest["spec"]) != original:
        raise RuntimeError("Workspace changed during preparation; retry with a new backup filename")

    result = execute_graphql(api, WRITE_QUERY, {
        "id": personal["id"],
        "entityName": args.entity,
        "projectName": args.project,
        "type": "project-view",
        "name": personal["name"],
        "displayName": personal["displayName"],
        "spec": json.dumps(proposed),
    })
    if result["upsertView"].get("inserted"):
        raise RuntimeError("Unexpected insertion instead of update; inspect the saved result")
    _, after = read_views(api, execute_graphql, args.entity, args.project)
    actual = json.loads(after[args.personal_view]["spec"])
    if actual != proposed:
        raise RuntimeError("Saved view differs from proposed view; inspect before claiming success")
    print("Updated the existing personal workspace and verified exact raw-spec readback.")


if __name__ == "__main__":
    main()
