"""Render the measured fixed-controller ledger and conditional weight bounds."""
import json
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
source=ROOT/'outputs/response_weight_audit_cpu/measurement.json'
s=json.loads(source.read_text())
labels=('A_arm_candidate','B_stop_candidate','C_hold_arms')

def arrays(c,key):
    terms={k:np.asarray(v) for k,v in c[key].items()}
    pressure=-terms['wholebody_hand_clearance']/.01
    pre=sum(v for k,v in terms.items() if k!='wholebody_hand_clearance')
    return terms,pressure,pre

def score(c,h,t=1,key='per_step_weighted_terms'):
    terms,p,pre=arrays(c,key)
    return (np.clip(pre+(t-1)*terms['tracking_root_field'],0,10000)-h*.02*p).mean(0)

def bound(c,key):
    terms,p,pre=arrays(c,key);base=np.clip(pre,0,10000).mean(0);p=p.mean(0)
    return base,p,(base[0]-base[1])/(.02*(p[0]-p[1]))

poke=s['encounters']['poke_front'];narrow=s['encounters']['narrow']
bp,pp,hp=bound(poke,'per_step_weighted_terms')
bn,pn,hn=bound(narrow,'AB_comparison_terms')
finite_discounted=[]
for encounter,key in ((poke,'per_step_weighted_terms'),(narrow,'AB_comparison_terms')):
    terms,pressure,pre=arrays(encounter,key)
    discount=.98**np.arange(len(pre))
    base=(discount[:,None]*np.clip(pre,0,10000)).sum(0)
    p=(discount[:,None]*pressure).sum(0)
    finite_discounted.append((base,p,(base[0]-base[1])/(.02*(p[0]-p[1]))))
lines=['# Measured response weights — CPU, 22 September 2026', '',
'**Recommendation: provisional hand clearance −5, tracking_root_field +1. Keep arm clearance −2 for this isolated change. Do not call this a globally calibrated safe pair.** The measured poke and passage thresholds are clearance magnitudes '+f'{hp:.6f} and {hn:.6f}, respectively. The proposed −20 also selects A in these measured comparisons; it is not refuted by this sample. No training or launch was performed.', '',
'**Scope / completeness:** real MuJoCo dynamics, actual production reward kernels, requested native warm-start policy, one deterministic seed (71), one front poke and one analytic narrow passage. This provides conditional finite-trace thresholds, not a global optimum or a statistical retention guarantee. Missing: full collision-bank acceptance, a multi-seed/direction/bank distribution bound, discounted whole-episode counterfactuals, and changed-policy clutter/narrow/CAT success measurements. The latter cannot be obtained from reward rescoring and were not invented.', '',
'Protocol: `scripts/measure_response_weights_cpu.py:1`; complete unrounded per-step terms: `outputs/response_weight_audit_cpu/measurement.json:1`. Frozen weights are read directly (mmap) from `outputs/cat_flat_balance_ppo_37632_20260920/resume.pt`; no copies or checkpoint/bank mutations. Config scales come from `outputs/cat_recover_23_30720_20260922/run.json`, with obsolete box rewards removed, native 222/310, noise/push/domain randomization disabled. No new avoidance flag. CPU threads=2; GPU driver was unavailable.', '',
'A is a bounded tucked-arm target intervention on the frozen walking controller; B obtains physically executed stopping/backing actions from the frozen controller using synthetic standing command/phase/guidance **only as controller inputs**, all restored before each physical step. C holds the onset arm targets. The true command stays 0.6 m/s and the true gait generator is unchanged for all three. Arms unchanged means unchanged motor targets, not perfectly rigid limb positions. A is approximately arm-led, not a perfectly constrained root path. These are feasible candidate action sequences, not claims that the unmodified policy selects them.', '',
'Poke: 6 cm sphere, initial 12 cm surface gap, 10 cm/s front approach, advected with matched C root, as in `scripts/diagnose_reactive_clearance_cpu.py:58`. Common horizon ends at C termination: '+f"{poke['steps']} steps / {poke['seconds']:.2f} s. Sphere post-termination traces are excluded from all reported comparisons.", '',
'Narrow: two finite analytic boxes, 74 cm opening, 60 cm length, 140 cm height, entry 80 cm ahead of onset root. Common A/B/C horizon: '+f"{narrow['steps']} steps / {narrow['seconds']:.2f} s (C terminates). A's root crosses the far gate at step {narrow['first_crossing_step'][0]} / {narrow['first_crossing_step'][0]*.02:.2f} s. B remains upstream (maximum forward travel {narrow['AB_body_max_forward_m']:.6f} m) and eventually backs away; A and B remain unterminated through that common full-crossing horizon. Root crossing is **not** full-body passage certification. Virtual analytic fields follow the poke diagnostic; full-body collision-bank events are not measured, so body_collision_event=0 is a scope limitation, not evidence of no proxy contacts.", '',
'Measured motion check (same JSON): at poke endpoint A root moved (0.546395, 0.083929, −0.021269) m and left hand relative to root moved (−0.050265, −0.207785, −0.154392) m. C root moved (0.529590, 0.005070, −0.019417) m; matched-control root-relative front retreat is therefore 3.908467 cm for A. A has 7.885939 cm more lateral root drift than C: **this does not realize an exactly arm-only response with identical base path.** The ledger is for measured arm-target, body, and hold interventions; an exact pure-A/identical-path ledger and its threshold remain unmeasured. In the full passage A root advances 1.401672 m with −0.010258 m lateral change; B retreats 2.085705 m with +0.741748 m lateral change. These show traversal versus body refusal, not immobility.', '',
'## Every contributing term, reward per 20 ms control step', '',
'Tables are arithmetic means of actual per-step contributions over identical, pre-first-termination A/B/C horizons. Raw per-step arrays are in the JSON. All terms already include dt=0.02; collision events, if measured, would not be dt scaled. Retired box and flat bonus terms are exactly zero in this configuration. The production non-hand floor lift is shown separately. Formula: R=max(0, sum(non-hand weighted terms)×dt)−H×pressure×dt (`cat_mjlab/task.py:536`, `cat_mjlab/reward_floor.py:13`). **Do not floor the total after adding hand clearance, or floor averaged terms.**', '']
for kind,c in s['encounters'].items():
    lines += ['### '+kind,'','| Term | A: −0.5 | B: −0.5 | C: −0.5 | A: −20 | B: −20 | C: −20 |','|---|---:|---:|---:|---:|---:|---:|']
    rows=[c['rows'][k] for k in labels]
    for term in rows[0]['ledger_current']:
        values=[r['ledger_current'][term] for r in rows]
        alt=[v*40 if term=='wholebody_hand_clearance' else v for v in values]
        lines.append('| '+term+' | '+' | '.join(f'{v:.9g}' for v in values+alt)+' |')
    lines.append('| **Actual total** | '+' | '.join(f'{v:.9g}' for v in list(score(c,.5))+list(score(c,20)))+' |')
    lines += ['',f"Highest measured mean: **{labels[int(score(c,.5).argmax())]} at −0.5; {labels[int(score(c,20).argmax())]} at −20.** This ranks only the three tested trajectories, not all possible responses.",'']
lines+=['### Full passage A versus B, 231-step common horizon','',
'Here C is excluded because it terminated at step 37; later autoreset samples are not valid C passage evidence. This table includes A’s actual far-gate crossing and the same elapsed refusal/backing time for B.','',
'| Term | Traverse A: −0.5 | Refuse B: −0.5 | Traverse A: −20 | Refuse B: −20 |','|---|---:|---:|---:|---:|']
terms,p,pre=arrays(narrow,'AB_comparison_terms')
for k,v in terms.items():
    means=v.mean(0)[:2];alt=means*(40 if k=='wholebody_hand_clearance' else 1)
    lines.append('| '+k+' | '+' | '.join(f'{x:.9g}' for x in [*means,*alt])+' |')
lift=(np.clip(pre,0,10000)-pre).mean(0)[:2]
lines+=['| reward_floor_lift | '+' | '.join(f'{x:.9g}' for x in [*lift,*lift])+' |',
        '| body_collision_event (not instrumented) | 0 | 0 | 0 | 0 |',
        '| **Total** | '+' | '.join(f'{x:.9g}' for x in [*score(narrow,.5,key='AB_comparison_terms')[:2],*score(narrow,20,key='AB_comparison_terms')[:2]])+' |','',
'## Threshold derivations', '',
'Let H=−hand_weight≥0, T=tracking weight, p=mean normalized hand pressure, and b(T)=mean of the **per-step floored** non-hand reward. For fixed measured trajectories, R_i(H,T)=b_i(T)−0.02 H p_i. A beats B iff b_A−b_B > 0.02 H(p_A−p_B). If p_A=p_B there is no hand-weight crossover. If p_A<p_B the inequality reverses. Raising T requires reapplying the floor to every sample, not adding a mean tracking term afterward.', '',
f'Front poke, T=1: b_A={bp[0]:.12g}, b_B={bp[1]:.12g}, p_A={pp[0]:.12g}, p_B={pp[1]:.12g}. Thus H_AB=({bp[0]:.12g}−{bp[1]:.12g})/[0.02×({pp[0]:.12g}−{pp[1]:.12g})] = **{hp:.6f}** (signed hand weight **−{hp:.6f}**). B wins above this magnitude, A below it. This large number extrapolates fixed traces far outside tested training; it is not a recommended weight.', '',
f'Full passage, T=1: b_A={bn[0]:.12g}, b_B={bn[1]:.12g}, p_A={pn[0]:.12g}, p_B={pn[1]:.12g}. H_refusal=({bn[0]:.12g}−{bn[1]:.12g})/[0.02×({pn[0]:.12g}−{pn[1]:.12g})] = **{hn:.6f}** (signed **−{hn:.6f}**). B has zero measured hand pressure and wins beyond that magnitude. Below it A wins this same-duration passage/refusal comparison.', '',
'At H=0 A already beats both alternatives in the two common encounter windows and beats B across the full traversal. Thus the measured intersection is **0≤H<'+f'{min(hp,hn):.6f} at T=1**, not an identified global usable interval. Clearance weight alone is not required to make this particular arm action attractive; failure to learn/use it cannot be diagnosed from coefficients alone.', '',
f'The source warm-start learner uses gamma=0.98 (read from resume.pt learner.config.discounting). Applying gamma**step to the saved traces gives finite-horizon discounted crossover magnitudes **{finite_discounted[0][2]:.6f}** (poke) and **{finite_discounted[1][2]:.6f}** (passage). The same quotient uses discounted sums: poke non-hand A/B={finite_discounted[0][0][0]:.9f}/{finite_discounted[0][0][1]:.9f}, pressure A/B={finite_discounted[0][1][0]:.9f}/{finite_discounted[0][1][1]:.9f}; passage non-hand A/B={finite_discounted[1][0][0]:.9f}/{finite_discounted[1][0][1]:.9f}, pressure A/B={finite_discounted[1][1][0]:.9f}/{finite_discounted[1][1][1]:.9f}. Unknown continuation values are omitted; these are not infinite-horizon policy-optimal thresholds.', '',
'## Owner hypotheses and recommendation','',
'(a) **Reject 20:1 as a general cost ratio; support arm preference only for these final, state-consistent traces.** Poke A−B tracking advantage is 0.009126501852 reward/step. Incremental target velocity+acceleration cost of A over B is 0.000019813208, a ratio of **460.63:1**, not 20:1. Velocity alone costs 0.000014358698. The A−C comparison gives a different ratio, **23.33:1**. Neither is the total ledger ratio: posture gating, handsdf, guidance, balance, torque and the floor all also change. Formulas normalize squared arm velocity/acceleration by joint weights, dt and scales (`cat_mjlab/task_math.py:138`); comparing −.05 to +1 misses those factors.', '',
'(b) **The maximum-bound arithmetic is correct, but the inference that −20 makes refusal optimal is not supported here.** Tracking max +1 and clearance max −20 are rates; at 20 ms their maxima are +0.02 and −0.40. The hand maximum requires both hands at/below zero surface gap. With one threatened hand and the other ≥20 cm, maximum is −0.20. At two-hand gaps 10 cm / 7.899 cm / 4 cm, the −20 penalties are respectively −0.020000 / −0.02928684 / −0.051200 per step, not −0.40 (`cat_mjlab/task_math.py:128`). At the measured full passage, −20 gives only '+f'{-.4*pn[0]:.9f} hand reward/step; the non-hand A−B advantage is {bn[0]-bn[1]:.9f}. A remains preferred.', '',
'**Provisional pair (−5,+1)** gives 10× the current hand coefficient, while remaining '+f'{hp/5:.1f}× below the poke and {hn/5:.1f}× below the passage crossover. At that pair, measured poke A/B/C rewards are '+', '.join(f'{v:.9f}' for v in score(poke,5))+', and full passage A/B are '+', '.join(f'{v:.9f}' for v in score(narrow,5,key='AB_comparison_terms')[:2])+'. The margins are empirical margins against these candidates only. Choosing −5 over −20 is a conservative design choice for unmeasured directions, not an experimentally identified optimum. **No tracking increase is needed in this sample.**', '',
'No single pair is proven to work across all tasks, and these results also do not prove that no such pair exists. Tracking penalizes velocity error, not world position: after a lateral detour, returning to commanded velocity can have identical tracking reward at a different position (`cat_mjlab/task_math.py:228`). Raising tracking therefore cannot guarantee path adherence. Production room commands may themselves become zero when route guidance is blocked (`cat_mjlab/task.py:239`), unlike this deliberately fixed-command audit. Global guarantees cannot be obtained from these two weights and two encounters.', '',
'**Retention risk:** unchanged frozen actions have exactly zero success-metric change under reward-only rescoring. That is not a training prediction. Raising T from 1 to 2 would add 0–0.02 pre-floor reward/step on *every* task (tracking raw in [0,1]); clipping can reduce the realized increment. There is no defensible measured conversion from that change to future clutter/narrow/CAT rates. User-supplied starting rates are .7137/.5582/.1495; without new learned-policy evidence their possible absolute changes are only trivially bounded by [−.7137,+.2863], [−.5582,+.4418], [−.1495,+.8505]. These are mathematical bounds, not forecasts. We keep T=1; clearance changes still carry unquantified retention risk. A proposed, unvalidated future acceptance tolerance of −.03 absolute would set floors .6837/.5282/.1195; this is a decision criterion, not measured risk.', '',
'## Elbows and forearms','',
'`docs/LATERAL_CORRIDOR_AUDIT_CPU_20260922.md:102` records ten hand-compliant endpoints below 78.99 mm elbow/forearm margin: minimum 66.41 mm, all-arm minimum 64.01 mm; no elbow/forearm collision in those hand-compliant samples. **78.99 mm was the hand-envelope target, not an established whole-arm guarantee of the old box.** Hand compliance does not certify elbow/forearm clearance.', '',
'The current arm term is −2×mean(max(0,.08−d_elbow)^2), with no normalization (`cat_mjlab/task.py:497`). If one of two elbow probes has the documented 66.41 mm gap and the other is ≥80 mm, this formula gives **−0.000003693762/step**; both at that gap give −0.000007387524. This is a formula evaluation at the documented capsule gap, **not a claim that the elbow point probe measured the identical distance**. The reward samples elbow points with 5 cm radii (`cat_mjlab/task.py:272`), whereas the audit uses whole-arm proxies. Multiplying −2 by 40 gives only −0.00014775048/step for one elbow at that gap. It is not comparable to normalized hand pressure.', '',
'**Do not move arm clearance in numerical lockstep.** Keep −2 for this isolated launch recommendation, but regard whole-arm margin protection as unverified. Meaningful elbow/forearm protection needs its own calibrated, normalized clearance term and matching proxy measurements; merely scaling this point-probe squared-metre hinge does not enforce 78.99 mm, especially inside the non-hand reward floor. No arm reward or geometry was silently changed.', '',
'## Implemented telemetry, tests and launch','',
'`cat_mjlab/response_split.py:1` defines per-environment events: onset at either hand <20 cm, closure when both ≥22 cm or at first outcome/termination. Lock threatened hand and outward normal at onset. Signed arm retreat is [(hand−root)_end−(hand−root)_start]·normal; world root displacement is ||root_end−root_start||, plus signed root retreat. This is the same translation-only subtraction as `scripts/diagnose_reactive_clearance_cpu.py:95`; root rotation is deliberately not removed. Unlike paired offline diagnostics, online events have no matched control, so normal gait swing/progress is included and these are not causal attributions.', '',
'Per-event outputs are `response_split/event_count`, `hand_relative_retreat_sum_m`, `root_world_displacement_sum_m`, `root_retreat_sum_m`, `ratio_sum`, `ratio_valid_count`, `zero_root_count`, `invalid_event_count` in transition metrics. Event_count masks individual records. Ratios are signed arm retreat / world-root displacement; root travel ≤1 mm is explicitly undefined and excluded from ratio means, not replaced with an enormous number. Training logs event-weighted means and pending-event counts under `training/response_split/`; passage acceptance logs the same sufficient statistics and ratios by existing cohorts. No unbounded event-history buffer or added observation features.', '',
'Wiring: `cat_mjlab/task.py:409` (reset state), `cat_mjlab/task.py:732` (pre-autoreset event capture), `cat_mjlab/runner.py:303` (training aggregation), `cat_mjlab/acceptance.py:125` (gate), and `cat_mjlab/acceptance.py:476` (offline world-sample adapter). State lives in the existing task info/checkpoint dictionary; legacy gate state is upgraded on load. Missing offline world samples/precomputed events cannot demonstrate an arm response; zero events are not evidence of success.', '',
'Validation: `tests/test_response_split.py:1` covers arm-only/body-only/mixed responses, undefined ratios, hysteresis, termination/reset, exact poke projection equivalence, collector logging without optimization, offline acceptance and checkpoint observer roundtrip, plus explicit tracking-weight override validation. Final focused suite: 63 passed, two unrelated synthetic runner fixtures deselected. Earlier broader checks: 66 passed; two legacy JAX parity tests could not import the absent mujoco_playground dependency. A separate full runner test attempt had two synthetic 3/4-observation fixtures rejected by the native 222/310 guard. No real optimizer updates or training run occurred. Test evidence: `outputs/response_weight_audit_cpu/tests.txt`.', '',
'Prepared command: `configs/pilots/clearance_weight_warmstart.sh:1`. Warm-start source is the requested resume.pt with a fresh optimizer, native observations, hand=−5, tracking=+1, W&B online / CAT-wholebody / skvayzer. The script was syntax/argument checked, **not executed**. This is a provisional measured-candidate recommendation, not authorization or a validated retention claim.', '']
out=ROOT/'docs/RESPONSE_WEIGHT_MEASUREMENT_20260922.md'
out.write_text('\n'.join(lines))
print(out)
